name: release
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Build
        run: |
          go version
          ./tools/build.sh
      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        with:
          name: artifacts
          path: ./releases

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        name: Download artifacts
        with:
          name: artifacts
          path: ./releases
      - name: Publish artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: "./releases/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
